import path from 'path';
import { readJsonFile, writeJsonFile } from '../src/context/io';
import { GeneratedFilesManifest, InitialContext } from '../src/context/types';

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function assertGeneratedFilesManifest(value: any): GeneratedFilesManifest {
  if (!value || !Array.isArray(value.files)) {
    throw new Error('Agent API response must include a files array');
  }
  for (const file of value.files) {
    if (!file || typeof file.path !== 'string' || typeof file.content !== 'string') {
      throw new Error('Each generated file must include string path and content');
    }
  }
  return value as GeneratedFilesManifest;
}

async function generateViaOpenAI(context: InitialContext): Promise<GeneratedFilesManifest> {
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || 'gpt-5.4';
  if (!apiKey) {
    throw new Error('OPENAI_API_KEY is required for api mode');
  }

  const system = [
    'You generate Jest unit tests for a PR based on provided context JSON.',
    'Hard constraints:',
    '- Output must be STRICT JSON only (no markdown).',
    '- Output must match this schema exactly: {"files":[{"path":"tests/generated/<name>.test.ts","content":"..."}],"notes":"..."}',
    '- You may only generate files under tests/generated/. No other paths.',
    '- Do not propose changes to production code. Only tests.',
    '- Keep tests minimal and focused on changed behavior.',
  ].join('\n');

  const user = [
    'Context JSON follows. Generate Jest tests accordingly.',
    JSON.stringify(context),
  ].join('\n');

  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model,
      input: [
        { role: 'system', content: [{ type: 'text', text: system }] },
        { role: 'user', content: [{ type: 'text', text: user }] },
      ],
      // Ask for JSON mode via response_format.
      response_format: { type: 'json_object' },
    }),
  });

  if (!response.ok) {
    throw new Error(`OpenAI API error ${response.status}: ${await response.text()}`);
  }

  const json = await response.json();
  // Responses API returns content in output_text; prefer that for strict JSON.
  const outputText = (json.output_text as string | undefined) || '';
  if (!outputText.trim()) {
    throw new Error('OpenAI response missing output_text');
  }

  let parsed: any;
  try {
    parsed = JSON.parse(outputText);
  } catch {
    throw new Error('OpenAI output_text was not valid JSON');
  }

  return assertGeneratedFilesManifest(parsed);
}

function generateStub(context: InitialContext): GeneratedFilesManifest {
  const sourceFiles = context.changedFiles.length > 0
    ? context.changedFiles
    : [{ path: 'src/example.ts' } as typeof context.changedFiles[number]];

  const files = sourceFiles.slice(0, 1).map((changedFile) => {
    const safeName = changedFile.path.replace(/[\\/]+/g, '__').replace(/\.(ts|tsx|js|jsx)$/, '');
    const targetPath = `tests/generated/${safeName}.test.ts`;
    const name = path.basename(changedFile.path).replace(/\.(ts|tsx|js|jsx)$/, '');
    return {
      path: targetPath,
      content: `describe('${name}', () => {\n  it('has generated placeholder coverage', () => {\n    expect(true).toBe(true);\n  });\n});\n`,
    };
  });

  return {
    files,
    notes: 'Generated by stub mode',
  };
}

async function main(): Promise<void> {
  const contextPath = argValue('--context') || 'artifacts/context/initial-context.json';
  const outPath = argValue('--out') || 'artifacts/generated/generated-files.json';
  const mode = argValue('--mode') || 'stub';
  const context = readJsonFile<InitialContext>(path.resolve(contextPath));

  const manifest = mode === 'api' ? await generateViaOpenAI(context) : generateStub(context);
  writeJsonFile(path.resolve(outPath), manifest);
  console.log(JSON.stringify({ ok: true, generatedFiles: manifest.files.length, mode }, null, 2));
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

export { assertGeneratedFilesManifest, generateStub };
