import path from 'path';
import { readJsonFile, writeJsonFile } from '../src/context/io';
import { GeneratedFilesManifest, InitialContext } from '../src/context/types';

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

function assertGeneratedFilesManifest(value: any): GeneratedFilesManifest {
  if (!value || !Array.isArray(value.files)) {
    throw new Error('Agent API response must include a files array');
  }
  for (const file of value.files) {
    if (!file || typeof file.path !== 'string' || typeof file.content !== 'string') {
      throw new Error('Each generated file must include string path and content');
    }
  }
  return value as GeneratedFilesManifest;
}

async function generateViaApi(context: InitialContext): Promise<GeneratedFilesManifest> {
  const url = process.env.AGENT_API_URL;
  const apiKey = process.env.AGENT_API_KEY;
  if (!url || !apiKey) {
    throw new Error('AGENT_API_URL and AGENT_API_KEY are required for api mode');
  }

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
    },
    body: JSON.stringify(context),
  });

  if (!response.ok) {
    throw new Error(`Agent API error ${response.status}: ${await response.text()}`);
  }

  const json = await response.json();
  return assertGeneratedFilesManifest(json);
}

function generateStub(context: InitialContext): GeneratedFilesManifest {
  const sourceFiles = context.changedFiles.length > 0
    ? context.changedFiles
    : [{ path: 'src/example.ts' } as typeof context.changedFiles[number]];

  const files = sourceFiles.slice(0, 1).map((changedFile) => {
    const safeName = changedFile.path.replace(/[\\/]+/g, '__').replace(/\.(ts|tsx|js|jsx)$/, '');
    const targetPath = `tests/generated/${safeName}.test.ts`;
    const name = path.basename(changedFile.path).replace(/\.(ts|tsx|js|jsx)$/, '');
    return {
      path: targetPath,
      content: `describe('${name}', () => {\n  it('has generated placeholder coverage', () => {\n    expect(true).toBe(true);\n  });\n});\n`,
    };
  });

  return {
    files,
    notes: 'Generated by stub mode',
  };
}

async function main(): Promise<void> {
  const contextPath = argValue('--context') || 'artifacts/context/initial-context.json';
  const outPath = argValue('--out') || 'artifacts/generated/generated-files.json';
  const mode = argValue('--mode') || 'stub';
  const context = readJsonFile<InitialContext>(path.resolve(contextPath));

  const manifest = mode === 'api' ? await generateViaApi(context) : generateStub(context);
  writeJsonFile(path.resolve(outPath), manifest);
  console.log(JSON.stringify({ ok: true, generatedFiles: manifest.files.length, mode }, null, 2));
}

if (require.main === module) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}

export { assertGeneratedFilesManifest, generateStub };
