import path from 'path';
import { readJsonFile, writeJsonFile } from '../src/context/io';
import { GeneratedFilesManifest, InitialContext } from '../src/context/types';

function argValue(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index >= 0 ? process.argv[index + 1] : undefined;
}

const contextPath = argValue('--context') || 'artifacts/context/initial-context.json';
const outPath = argValue('--out') || 'artifacts/generated/generated-files.json';
const mode = argValue('--mode') || 'stub';

const context = readJsonFile<InitialContext>(path.resolve(contextPath));

const sourceFiles = context.changedFiles.length > 0
  ? context.changedFiles
  : [{ path: 'src/example.ts' } as typeof context.changedFiles[number]];

const files = sourceFiles.slice(0, 1).map((changedFile) => {
  const targetPath = changedFile.path.replace(/\.(ts|tsx|js|jsx)$/, '.test.ts');
  const name = path.basename(changedFile.path).replace(/\.(ts|tsx|js|jsx)$/, '');
  const importPath = './' + path.basename(changedFile.path).replace(/\.(ts|tsx|js|jsx)$/, '');
  return {
    path: targetPath,
    content: `describe('${name}', () => {\n  it('has generated placeholder coverage', () => {\n    expect(true).toBe(true);\n  });\n});\n`,
  };
});

const manifest: GeneratedFilesManifest = {
  files,
  notes: mode === 'stub' ? 'Generated by stub mode' : 'Generated by external mode placeholder',
};

writeJsonFile(path.resolve(outPath), manifest);
console.log(JSON.stringify({ ok: true, generatedFiles: files.length, mode }, null, 2));
